imports:
    - { resource: "@SetonoSyliusCalloutPlugin/Resources/config/app/grids.yaml" }
    - { resource: "@SetonoSyliusCalloutPlugin/Resources/config/app/sylius_ui.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_callout.command_bus: ~
